[package]
name = "retro-cell"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic-wait = "1.1.0"
loom = { version = "0.7", optional = true }

[features]
default = []
loom = ["dep:loom"]

[dev-dependencies]
criterion = "0.7.0"
arc-swap = "1.7.1"

[[bench]]
name = "performance"
harness = false
